### ISSUE TITLE
Flagging of Dissimilar Cells is Unclear

### ISSUE THREAD

**Issue by DarioS** [Genentech/scimilarity#4]
> Low SCimilarity scores to reference cells flag an outlier query cell, which may be either a cell type that is not within the reference or a query cell of low quality.

What is the definition of "low" and how are such cells distinguished in the output? It isn't explained in the user guide.

**Comment by gheimberg** [comment]
Unfortunately there is no great answer for this. It will take a little exploration as it depends on your task and I presume is different for different cell types. In the manuscript we use 0.03 for the MoMac classification (which I feel was relatively stringent). 

The good news is that since each cell is handled independently throughout the SCimilarity workflow, you can always skip filtering cells for now and come back to it later. For example, if some cells are junk and should be filtered, they will get funky classifications and then will not affect the classification of any other cells. If you see unexpected cell types, e.g. hepatocytes in a lung tissue sample, then I would go check that `min_dist` field and adjust your filters.
